[package]
name = "ros_wrapper"
version = "0.1.0"
edition = "2024"

[lib]
name = "ros_wrapper"
path = "src/lib.rs"

[dependencies]
r2r = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros", "sync"] }
futures = "0.3"
