[package]
name = "cam_test"
version = "0.1.0"
edition = "2024"

[dependencies]
ros_wrapper = { path = "../ros_wrapper" }
v4l = { version = "0.14.0", features = ["libv4l"] }
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros"] }
image = "0.25"
