[package]
name = "tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
ros_wrapper = { path = "../ros_wrapper" }
software_pwm = { path = "../software_pwm" }
tokio = { version = "1", features = ["rt-multi-thread", "time", "sync"] }
